name: Go Test

on:
  # プッシュとプルリクエストで実行
  push:
  pull_request:

jobs:
  build:
    # 最新のUbuntuランナーを使用
    runs-on: ubuntu-latest
    steps:
      # リポジトリのコードをチェックアウト
      - uses: actions/checkout@v3
      # 指定されたGoのバージョンをインストール
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      # 単体テストを実行
      - name: Run tests
        run: go test ./...
      # 静的解析を実行
      - name: Run go vet
        run: go vet ./...
      # golangci-lintで追加のチェックを実行
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54.1
